name: Release
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - uses: changesets/action@v1
              with:
                  version: npm run version-packages
                  publish: npm run release
                  createGithubReleases: true
              env:
                  NPM_CONFIG_PROVENANCE: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
